<?php

/**
 * Implements hook_preprocess_page().
 */
function gallerysite_preprocess_page(&$vars) {
  drupal_set_message(t('This is a pre-launch version of The Gallery Guide. Please go to <a href="http://www.thegalleryguide.co.uk">the live site</a> to log in or edit content.'));
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gallerysite_form_node_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Remove revision log fields
  $form['revision_information']['#access'] = FALSE;

  // Remove preview functionality.
  $form['actions']['preview']['#access'] = FALSE;

  // Remove votes open/closed.
  $form['field_rating']['#access'] = FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gallerysite_form_node_gallery_delete_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Prevent deletion if the gallery has any exhibitions.

}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gallerysite_form_user_register_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Hide the content form options.
  $form['contact']['#type'] = 'hidden';
}
