<?php

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gallerysite_form_taxonomy_term_artists_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  // Remove votes open/closed.
  $form['field_rating']['#access'] = FALSE;

  // Remove relations section.
  $form['relations']['#access'] = FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gallerysite_form_node_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Remove revision log fields
  $form['revision_information']['#access'] = FALSE;

  // Remove preview functionality.
  $form['actions']['preview']['#access'] = FALSE;

  // Remove votes open/closed.
  $form['field_rating']['#access'] = FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gallerysite_form_node_gallery_delete_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Prevent deletion if the gallery has any exhibitions.

}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gallerysite_form_contact_message_contact_us_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Remove preview option from contact form.
  $form['actions']['preview']['#access'] = FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gallerysite_form_user_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Hide the content form options.
  $form['contact']['#access'] = FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gallerysite_form_user_register_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Hide the content form options.
  $form['contact']['#access'] = FALSE;
}

function gallerysite_default_image() {

  $connection = Database::getConnection();
  
  $query = $connection->select('file_managed', 'fm')
    ->condition('uri', 'public://imagefield_default_images/anon_large.gif')
    ->fields('fm', array('fid', 'uuid'))
    ->execute();
  
//  $connection->update('file_managed', 'fm')
//    ->condition('fid')

  
}
